[legends]
U_EXLM = !
KC_EXLM = !
U_QUES = ? !
KC_QUES = ? !
KC_GT = >
KC_LT = <
KC_HASH = #
KC_PERC = %
KC_AT = @
KC_DLR = $
KC_CIRC = ^
KC_LCBR = {
KC_LPRN = (
KC_LBRC = [
KC_RCBR = }
KC_RPRN = )
KC_RBRC = ]
KC_PIPE = |
KC_GRV = `
KC_TILD = ~
KC_PLUS = +
KC_AMPR = &
KC_UNDS = _
KC_MINS = - _
KC_EQL = =
U_SL = / \
KC_SLSH = / ?
U_COMM = , <
KC_COMM = , <
KC_DOT = . >
KC_ASTR = *
KC_BSLS = \ |
KC_BSLASH = \ |
U_QUOT = ' "
KC_QUOT = ' "
KC_SCLN = : ;
KC_PSCR = PrintSc
KC_NLCK = NumLock
KC_SLCK = ScrLock
KC_INS = Ins
_ =
__ =

KC_MS_U = MOUSE ↑
KC_MS_D = MOUSE ↓
KC_MS_L = MOUSE ←
KC_MS_R = MOUSE →
KC_WH_U = WHEEL ↑
KC_WH_D = WHEEL ↓
KC_WBAK = ⯬
KC_WFWD = ⯮

C(KC_A) = Ctrl+A
C(KC_B) = Ctrl+B
C(KC_C) = Ctrl+C
C(KC_D) = Ctrl+D
C(KC_E) = Ctrl+E
C(KC_F) = Ctrl+F
C(KC_G) = Ctrl+G
C(KC_H) = Ctrl+H
C(KC_I) = Ctrl+I
C(KC_J) = Ctrl+J
C(KC_K) = Ctrl+K
C(KC_L) = Ctrl+L
C(KC_M) = Ctrl+M
C(KC_N) = Ctrl+N
C(KC_O) = Ctrl+O
C(KC_P) = Ctrl+P
C(KC_Q) = Ctrl+Q
C(KC_R) = Ctrl+R
C(KC_S) = Ctrl+S
C(KC_T) = Ctrl+T
C(KC_U) = Ctrl+U
C(KC_V) = Ctrl+V
C(KC_W) = Ctrl+W
C(KC_X) = Ctrl+X
C(KC_Y) = Ctrl+Y
C(KC_Z) = Ctrl+Z

KC_LGUI = LGUI ◆
KC_RGUI = RGUI ◆
KC_LALT = LALT ⎇
KC_RALT = AltGr
KC_LSFT = LSFT ⇧
KC_RSFT = RSFT ⇧
KC_LCTL = LCTL ⎈
KC_RCTL = RCTL ⎈

HOME_A = A/◆
HOME_B = B
HOME_C = C
HOME_D = D
HOME_E = E/⇧
HOME_F = F
HOME_G = G
HOME_H = H
HOME_I = I/⎇
HOME_J = J
HOME_K = K
HOME_L = L
HOME_M = M
HOME_N = N/⎈
HOME_O = O/◆
HOME_P = P
HOME_Q = Q
HOME_R = R/⎇
HOME_S = S/⇧
HOME_T = T/⎈
HOME_U = U
HOME_V = V
HOME_W = W
HOME_X = X
HOME_Y = Y
HOME_Z = Z

CTL_ESC = ESC/⎈
CTL_QUOT= ' "/⎈
ALT_ENT = ⏎ /⎇
KC_APP = MENU

NAV_TAB = TAB/NAV
MS_CAPS = CAPS/MS
SYM_ENT = ⏎/SYM
NAV_UND = _/NAV

OS_LSFT = 1-SHOT⇧
OS_RSFT = 1-SHOT⇧

E_ACUTE = É
C_CDILA = Ç
DED_CIR = ^
DED_UML = ¨

ARROW_R = -> =>

GUILL_R = »
GUILL_L = «
UPDIR = ../
E_GRAVE = È
A_GRAVE = À
YICODE = $yi{

TD_DOT = . >

NK_ON = NKROon
NK_OFF = NKROoff

STN_N1 = #1
STN_N2 = #2
STN_N3 = #3
STN_N4 = #4
STN_N5 = #5
STN_N6 = #6
STN_N7 = #7
STN_N8 = #8
STN_N9 = #9
STN_NA = NA
STN_S1 = S1
STN_TL = T-
STN_PL = P-
STN_HL = H-
STN_ST1 = *1
STN_ST3 = *3
STN_FR = -F
STN_PR = -P
STN_LR = -L
STN_TR = -T
STN_DR = -D
STN_S2 = S2
STN_KL = K-
STN_WL = W-
STN_RL = R- 
STN_ST2 = *2
STN_ST4 = *4
STN_RR = -R
STN_BR = -B
STN_GR = -G
STN_SR = -S
STN_ZR = -Z
STN_A = A-
STN_O = O-
STN_E = -E
STN_U = -U

SH_OS = SWAPHNDS
